version: '3.8'

services:
  jenkins:
    image: jenkins/jenkins:lts
    container_name: jenkins
    ports:
      - "8085:8080"
      - "50000:50000"
    volumes:
      - jenkins_home:/var/jenkins_home
      - ./jenkins-config.yaml:/var/jenkins_home/jenkins.yaml
    restart: unless-stopped

volumes:
  jenkins_home: